import Head from 'next/head';

import Grid from '../Grid/Grid';

export type PropTypes = {
  title: string;
  blocks?: any[];
};

export const GridPage = ({ title, blocks }: PropTypes) => (
  <>
    <Head>
      <title>{title}</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Grid blocks={blocks || []} />
  </>
);

export default GridPage;
