fragment LandingPageParts on LandingPage {
  title
  description
  published
  blocks {
    __typename
    ... on LandingPageBlocksHero {
      href
      title
      description
    }
    ... on LandingPageBlocksFeature {
      href
      title
      description
      deco {
        __typename
        slant
        background
      }
    }
  }
}

fragment PageParts on Page {
  title
  description
  published
  body
}

fragment TagParts on Tag {
  name
  slug
  description
}

fragment StuffParts on Stuff {
  title
  description
  published
  slug
  date
  tags
  iframe
  source
  body
}
