fragment LandingPageParts on LandingPage {
  title
  seo {
    __typename
    title
    description
  }
  blocks {
    __typename
    ... on LandingPageBlocksHero {
      href
      title
      description
    }
    ... on LandingPageBlocksFeature {
      href
      title
      description
      deco {
        __typename
        slant
        background
      }
    }
  }
}

fragment PageParts on Page {
  title
  seo {
    __typename
    description
  }
  excerpt
  body
}

fragment TagParts on Tag {
  name
  slug
  description
}

fragment StuffParts on Stuff {
  title
  description
  slug
  date
  seo {
    __typename
    title
    description
  }
  tags
  iframe
  source
  body
}

fragment PostParts on Post {
  title
  slug
  excerpt
  tags
  date
  body
}
