import Head from 'next/head';
import { LayoutContentWrapper } from '../../components/Layout/Layout';
import { DraftLink as Link } from '../../components/Link/Link';
import filterUnpublished from '../../lib/filterUnpublished';
import getBlogContext from '../../lib/getBlogContext';
import { AsyncReturnType } from '../../typings';

const Blog = (props: AsyncReturnType<typeof getStaticProps>['props']) => {
  return (
    <LayoutContentWrapper>
      <Head>
        <title>Blog</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Blog</h1>

      <ul>
        {props.data.posts.map((post) => (
          <li key={post.href}>
            <Link unpublished={!post?.published} href={post.href}>
              {post.title}
            </Link>
          </li>
        ))}
      </ul>
    </LayoutContentWrapper>
  );
};

export default Blog;

export const getStaticProps = async function () {
  const postsListData = await getBlogContext();
  return {
    props: {
      data: {
        posts: filterUnpublished(Object.values(postsListData)),
      },
    },
  };
};
