import Head from 'next/head'

import { ExperimentalGetTinaClient } from '../.tina/__generated__/types'
import Blocks from '../components/Blocks/Blocks'
import { useStyles as useLayoutStyles } from '../components/Layout/Layout';
import { getPageContext } from "../lib/getPageContext"

const Home = ({ pageContext, ...props }: AsyncReturnType<typeof getStaticProps>['props']) => {
  const { classes: { main } } = useLayoutStyles()
  const data = props.data?.getLandingPageDocument?.data || {}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={main}>
        <Blocks blocks={data.blocks || []} />
      </div>
    </>
  )
}

export default Home

// Data Fetching
export const getStaticProps = async function () {
  const client = ExperimentalGetTinaClient()
  const vars = { relativePath: 'home.json' }
  return {
    props: {
      pageContext: await getPageContext(),
      ...(await client.getLandingPageDocument(vars))
    }
  }
}
