# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy-ftp-zeropaper-style

on:
  push:
    branches: [redesign]
  # pull_request:
  #   branches: [ redesign ]

jobs:
  qa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # - 10.x
          # - 12.8
          # - 14.x
          - 16.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/main/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/main/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  build:
    needs: qa
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # - 10.x
          # - 12.8
          # - 14.x
          - 16.x

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout current
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/main/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: sites/zeropaper.style/
